{% set name = "speedscope" %}
{% set version = "1.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jlfwong/speedscope/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4648299733f4c516a4c373cb566462938f7ad48b908a9048e77abb18b5e153d7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
    - pnpm-licenses
  run:
    - nodejs
test:
  commands:
    - speedscope --help

about:
  home: https://github.com/jlfwong/speedscope
  summary: A fast, interactive web-based viewer for performance profiles.
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - moritzwilksch
