{% set name = "speedscope" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jlfwong/speedscope/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 903bc7bf17a0ba0c09ca9f6febd46dfaf8cc8b42c085a6a9e9405a968201353b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
  host:
    - nodejs
    - pnpm >=8.6.12
    - pnpm-licenses
  run:
    - nodejs
test:
  commands:
    - speedscope --help

about:
  home: https://github.com/jlfwong/speedscope
  summary: A fast, interactive web-based viewer for performance profiles.
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - moritzwilksch
